CREATE PROCEDURE ADICIONAGERENTE
	@NOME VARCHAR(100)
	,@RG CHAR(9)
	,@CPF CHAR(11)
AS
BEGIN
	INSERT INTO GERENTE_EMPRESA(NOME,RG,CPF)
	VALUES (@NOME,@RG,@CPF)
END

CREATE PROCEDURE ListarGerenteS
AS
BEGIN
	SELECT NOME FROM GERENTE_EMPRESA
END

EXEC ADICIONAGERENTE 'Fernando','123456789','11122234566'

EXEC ListarGerenteS