CREATE DATABASE CEP1;
USE CEP1;

CREATE TABLE ENDERECOS(
	CEP INT
	, NOME VARCHAR(250)
	, CIDADE VARCHAR (250)
	, BAIRRO VARCHAR (250)
	, RUA VARCHAR (250)
	
);

CREATE TABLE ENDERECOS_CLUSTERIZADOS(
	CEP INT primary key
	, NOME VARCHAR(250)
	, CIDADE VARCHAR (250)
	, BAIRRO VARCHAR (250)
	, RUA VARCHAR (250)
	
);