SELECT COUNT(*) AS QUANTIDADE_REGISTROS FROM ENDERECOS;
SELECT COUNT(*) AS QUANTIDADE_REGISTROS FROM ENDERECOS_CLUSTERIZADOS;


SELECT * FROM ENDERECOS WHERE CEP= 06210030;

SELECT * FROM ENDERECOS_CLUSTERIZADOS WHERE CEP= 06210030;