--CRIA UM NOVO BANCO DE DADOS
CREATE DATABASE SENAI_DDL_REVISAO_TARDE;

--USA BANCO REVISAO TARDE
USE SENAI_DDL_REVISAO_TARDE;

-- CRIA UMA TABELA USUARIOS
CREATE TABLE USUARIOS(
	 --DEFINE QUE O ID SERÁ DO TIPO INT, AUTO INCRMENTO E CHAVE PRIMÁRIA
	 ID INT IDENTITY PRIMARY KEY
	 --DEFINE QUE A COLUNA EMAIL TERÁ ATÉ 250 CARACTERES, 
	 --NÃO PODE SER NULO E SEU VALOR DEVE SER UNICO
	,EMAIL VARCHAR(250) NOT NULL UNIQUE
	,SENHA VARCHAR(100) NOT NULL 
	,ATIVO BIT
);

--ADICIONA O CAMPO NOME NA TABELA USUARIOS
ALTER TABLE USUARIOS
ADD NOME VARCHAR(200)

--ADICIONA O CAMPO ATIVO NA TABELA USUARIOS
ALTER TABLE USUARIOS
ADD ATIVO BIT 

--EXCLUI A COLUNA NOME DA TABELA USUARIOS
ALTER TABLE USUARIOS
DROP COLUMN NOME

--EXCLUI A TABELA USUARIOS
DROP TABLE USUARIOS