CREATE DATABASE SENAI_DDL_REVISAO_MANHA;

USE SENAI_DDL_REVISAO_MANHA

/*
CRIA TABELA USUARIOS E DEFINE OS CAMPOS
*/
CREATE TABLE USUARIOS (
	 ID INT IDENTITY PRIMARY KEY
	,EMAIL VARCHAR(250) NOT NULL UNIQUE
	,SENHA VARCHAR(100) NOT NULL 
);

--ALTERA A TABELA USUARIOS E ADCIONA UMA COLUNA
ALTER TABLE USUARIOS
ADD ATIVO CHAR(1);

-- APAGA A TABELA
DROP TABLE USUARIOS;

--ALTERA A TABELA E REMOVE A COLUNA
ALTER TABLE USUARIOS
DROP COLUMN ATIVO;