CREATE DATABASE MAIA_FUNCOES;

USE MAIA_FUNCOES;

CREATE TABLE USUARIOS(
	ID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(255) NOT NULL
	,EMAIL VARCHAR(255) NOT NULL UNIQUE
	,SENHA VARCHAR(255) NOT NULL
	,CPF CHAR(11) NOT NULL UNIQUE
); 

INSERT INTO USUARIOS (NOME, SENHA, EMAIL, CPF) VALUES ('NOME A', '123456', 'A@A.A', '123');
INSERT INTO USUARIOS (NOME, SENHA, EMAIL, CPF) VALUES ('NOME B', '123456', 'A@A.B', '1234');
INSERT INTO USUARIOS (NOME, SENHA, EMAIL, CPF) VALUES ('NOME C', '123456', 'A@A.C', '321');
INSERT INTO USUARIOS (NOME, SENHA, EMAIL, CPF) VALUES ('NOME D', '123456', 'A@A.D', '123456');

CREATE FUNCTION BUSCAPORCPF(@CPFRECEBIDO CHAR(11))
RETURNS TABLE
AS
RETURN SELECT NOME, CPF FROM USUARIOS WHERE CPF = @CPFRECEBIDO;

SELECT * FROM BUSCAPORCPF('123');
SELECT * FROM USUARIOS WHERE CPF = '123';